name: Publish (TestPyPI)

on:
  push:
    tags:
      - 'v*.*.*-rc*'   # e.g., v0.1.0-rc1, v1.2.3-rc4

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install build twine tomli

      - name: Check tag vs pyproject version (RC allows suffix)
        run: |
          TAG="${GITHUB_REF_NAME#v}"            # e.g. 0.1.0-rc1
          BASE="${TAG%%-*}"                     # -> 0.1.0
          PYVER=$(
          python - <<'PY'
          import tomli, pathlib
          data = tomli.loads(pathlib.Path("pyproject.toml").read_text(encoding="utf-8"))
          print(data["project"]["version"])
          PY
          )
          echo "Tag: $TAG  Base: $BASE  pyproject: $PYVER"
          [ "$BASE" = "$PYVER" ] || { echo "Version mismatch: $BASE (tag base) != $PYVER (pyproject)"; exit 1; }

      - name: Build sdist & wheel
        run: python -m build

      - name: Twine check
        run: twine check dist/*

      - name: Upload dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-testpypi
          path: dist/*

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
